### ISSUE TITLE
Some 1.54" display links in README 404.

### ISSUE THREAD

**Issue by shymega** [caemor/epd-waveshare#161]
Hi,

I'm trying to work out if my e-ink display is supported by this library. I was looking at the 1.54" display links and two 404 for me. I've made a PR since to organize the list, so this issue might be outdated if that's merged, but the following links are 404'ing.

1.54 Inch B/W/Y (C): https://www.waveshare.com/1.54inch-e-paper-c.htm
1.54 Inch B/W/R (B): https://www.waveshare.com/product/modules/oleds-lcds/e-paper/1.54inch-e-paper-module-b.htm

The other 1.54" display link is fine.

Is there a link we should be using instead of these broken links?

Cheers.

**Comment by caemor** [comment]
Resolved by #160

**Comment by shymega** [comment]
@caemor #160 didn't resolve this error - it was a tidying-up commit, but two of the 1.54" displays are still 404'ing.

Can we re-open this issue?

**Comment by caemor** [comment]
Sure

**Comment by shymega** [comment]
Thanks. I don't know if those 404'ing links have a model number, but should be easy to find - I imagine?

**Comment by shymega** [comment]
OK, so I've found the 'B' display, but 'C' is missing.

I think the best approach is to nullify the URI for the 1.54 ('C') display and update the 'B' display's link. We can add a note to the 'C' display, and say it's no longer available; which is what it would seem.

I can submit a PR now if that's a good plan?

**Comment by caemor** [comment]
Sounds good to me :+1:

**Comment by shymega** [comment]
Do you think it's worth contacting Waveshare to enquire if the link will come back? I hope it will. I don't mind submitting an email and forwarding their response to you if you would like me to.

**Comment by shymega** [comment]
PR created.

**Comment by caemor** [comment]
> Do you think it's worth contacting Waveshare to enquire if the link will come back? I hope it will. I don't mind submitting an email and forwarding their response to you if you would like me to.

You can try if you want. But most likely they are just not selling that display anymore.

**Comment by shymega** [comment]
I've had a response.

In terms of README changes, they've given me a new URL, but it has also been discontinued. For reference purposes, I think it's best I open a new PR correcting the link.
